# Stage 1: Build the frontend
FROM --platform=$BUILDPLATFORM node:20-alpine AS build

WORKDIR /app

# Copy package.json and package-lock.json for dependency installation.
COPY frontend/package*.json ./
RUN npm ci

# Copy the rest of the frontend source code.
COPY frontend/. .
RUN npm run build

# Stage 2: Serve the frontend using Nginx.
FROM nginx:alpine AS final

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]