name: Build and Push Images

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 061391278883.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api:
              - 'FleetPulse.Api/**'
              - 'FleetPulse.Infrastructure/**'
              - 'FleetPulse.Contracts/**'

            worker:
              - 'FleetPulse.Worker/**'
              - 'FleetPulse.Infrastructure/**'
              - 'FleetPulse.Contracts/**'

            frontend:
              - 'frontend/**'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::061391278883:role/FleetPulseGitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build API image
        if: steps.changes.outputs.api == 'true'
        run: |
          docker build \
            --platform linux/arm64 \
            -t $ECR_REGISTRY/fleetpulse/api:$IMAGE_TAG \
            -t $ECR_REGISTRY/fleetpulse/api:latest \
            -f ./FleetPulse.Api/dockerfile \
            .

      - name: Push API image
        if: steps.changes.outputs.api == 'true'
        run: |
          docker push $ECR_REGISTRY/fleetpulse/api:$IMAGE_TAG
          docker push $ECR_REGISTRY/fleetpulse/api:latest

      - name: Build Worker image
        if: steps.changes.outputs.worker == 'true'
        run: |
          docker build \
            --platform linux/arm64 \
            -t $ECR_REGISTRY/fleetpulse/worker:$IMAGE_TAG \
            -t $ECR_REGISTRY/fleetpulse/worker:latest \
            -f ./FleetPulse.Worker/dockerfile \
            .

      - name: Push Worker image
        if: steps.changes.outputs.worker == 'true'
        run: |
          docker push $ECR_REGISTRY/fleetpulse/worker:$IMAGE_TAG
          docker push $ECR_REGISTRY/fleetpulse/worker:latest

      - name: Build Frontend image
        if: steps.changes.outputs.frontend == 'true'
        run: |
          docker build \
            --platform linux/arm64 \
            -t $ECR_REGISTRY/fleetpulse/frontend:$IMAGE_TAG \
            -t $ECR_REGISTRY/fleetpulse/frontend:latest \
            -f ./frontend/Dockerfile \
            .

      - name: Push Frontend image
        if: steps.changes.outputs.frontend == 'true'
        run: |
          docker push $ECR_REGISTRY/fleetpulse/frontend:$IMAGE_TAG
          docker push $ECR_REGISTRY/fleetpulse/frontend:latest'

      - name: Download API task definition
        if: steps.changes.outputs.api == 'true'
        run: |
          aws ecs describe-task-definition \
            --task-definition fleetpulse-api \
            --region $AWS_REGION \
            --query taskDefinition > task-definition.json

      - name: Render API task definition with new image tag
        if: steps.changes.outputs.api == 'true'
        id: render-api
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: fleetpulse-api
          image: ${{ env.ECR_REGISTRY }}/fleetpulse/api:${{ env.IMAGE_TAG }}

      - name: Deploy API to Amazon ECS
        if: steps.changes.outputs.api == 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-api.outputs.task-definition }}
          service: fleetpulse-api
          cluster: fleetpulse
          wait-for-service-stability: true

      - name: Download Worker task definition
        if: steps.changes.outputs.worker == 'true'
        run: |
          aws ecs describe-task-definition \
            --task-definition fleetpulse-worker \
            --region $AWS_REGION \
            --query taskDefinition > task-definition.json

      - name: Render Worker task definition with new image tag
        if: steps.changes.outputs.worker == 'true'
        id: render-worker
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: fleetpulse-worker
          image: ${{ env.ECR_REGISTRY }}/fleetpulse/worker:${{ env.IMAGE_TAG }}

      - name: Deploy Worker to Amazon ECS
        if: steps.changes.outputs.worker == 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-worker.outputs.task-definition }}
          service: fleetpulse-worker
          cluster: fleetpulse
          wait-for-service-stability: true